import React from 'react';
import { ArrowLeft, Flag, Mail, ShieldCheck, FileText } from 'lucide-react';
import { legalPages } from '../data/legal';
import { supportTopics } from '../data/support';
import { AppScreen } from '../types';

type LegalKey = keyof typeof legalPages;
interface LegalScreenProps { page: LegalKey | 'support'; onBack: () => void; onNavigate: (screen: AppScreen) => void; }

export const LegalScreen: React.FC<LegalScreenProps> = ({ page, onBack, onNavigate }) => {
  if (page === 'support') return <div className="min-h-screen bg-[#0A0A0A] text-[#F5F2ED] px-4 py-6 pb-28"><div className="max-w-3xl mx-auto"><button onClick={onBack} className="p-2 rounded-lg border border-white/10 hover:bg-white/5"><ArrowLeft className="w-4 h-4" /></button><div className="mt-6"><div className="text-[10px] uppercase tracking-[0.3em] text-white/40 font-mono">NextMarga Support</div><h1 className="font-serif-luxury text-3xl mt-2">Help & report an issue</h1><p className="text-sm text-white/55 mt-2">Found a broken opportunity or need help with your account? Choose the closest category below.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{supportTopics.map((topic) => <div key={topic.id} className="rounded-2xl border border-white/10 bg-[#121212] p-5"><div className="flex items-start gap-3"><div className="p-2 rounded-lg border border-white/10 bg-white/5"><Flag className="w-4 h-4 text-white/65" /></div><div><h2 className="text-sm">{topic.title}</h2><p className="text-xs text-white/45 mt-1 leading-relaxed">{topic.description}</p></div></div></div>)}</div><div className="mt-6 rounded-2xl border border-white/10 bg-[#121212] p-5"><div className="flex items-center gap-3"><Mail className="w-4 h-4 text-white/55" /><div><div className="text-xs">Need direct support?</div><div className="text-[11px] text-white/40 mt-1">Use the support/contact address configured for your NextMarga deployment.</div></div></div></div></div></div>;

  const content = legalPages[page];
  const Icon = page === 'privacy' ? ShieldCheck : page === 'terms' ? FileText : Flag;
  return <div className="min-h-screen bg-[#0A0A0A] text-[#F5F2ED] px-4 py-6 pb-28"><div className="max-w-3xl mx-auto"><button onClick={onBack} className="p-2 rounded-lg border border-white/10 hover:bg-white/5"><ArrowLeft className="w-4 h-4" /></button><div className="mt-6 flex items-start gap-4"><div className="p-3 rounded-xl border border-white/10 bg-[#121212]"><Icon className="w-5 h-5 text-white/70" /></div><div><div className="text-[10px] uppercase tracking-[0.3em] text-white/40 font-mono">NextMarga Trust</div><h1 className="font-serif-luxury text-3xl mt-1">{content.title}</h1><p className="text-[10px] text-white/30 mt-2 uppercase tracking-[0.16em]">Updated {content.updated}</p></div></div><div className="mt-7 space-y-3">{content.sections.map(([heading, body]) => <section key={heading} className="rounded-2xl border border-white/10 bg-[#121212] p-5"><h2 className="text-sm font-medium">{heading}</h2><p className="text-xs text-white/55 mt-2 leading-relaxed">{body}</p></section>)}</div><div className="mt-6 flex flex-wrap gap-2"><button onClick={() => onNavigate('legal-privacy')} className="px-3 py-2 rounded-lg border border-white/10 text-[10px] text-white/55 hover:text-white">Privacy</button><button onClick={() => onNavigate('legal-terms')} className="px-3 py-2 rounded-lg border border-white/10 text-[10px] text-white/55 hover:text-white">Terms</button><button onClick={() => onNavigate('legal-verification')} className="px-3 py-2 rounded-lg border border-white/10 text-[10px] text-white/55 hover:text-white">Verification</button><button onClick={() => onNavigate('support')} className="px-3 py-2 rounded-lg border border-white/10 text-[10px] text-white/55 hover:text-white">Support</button></div></div></div>;
};
