import React, { useEffect, useState } from 'react';
import { ArrowLeft, Bell, Check, ChevronRight, ExternalLink, Github, Instagram, LogOut, Palette, RotateCcw, Shield, Sparkles, UserRound, FileText, Flag } from 'lucide-react';
import { AppScreen } from '../types';

export type ThemeMode = 'light';
export type Accent = 'ivory' | 'blue' | 'violet' | 'emerald' | 'amber';
export interface AppPreferences { theme: ThemeMode; accent: Accent; compactMode: boolean; reducedMotion: boolean; notifications: boolean; }
const defaults: AppPreferences = { theme: 'light', accent: 'blue', compactMode: false, reducedMotion: false, notifications: true };
export const getPreferences = (): AppPreferences => { try { return { ...defaults, ...JSON.parse(localStorage.getItem('nextmarga_preferences') || '{}') }; } catch { return defaults; } };
interface SettingsScreenProps { onBack: () => void; onNavigate: (screen: AppScreen) => void; onPreferencesChange?: (prefs: AppPreferences) => void; onSignOut?: () => void; }
const accents: { id: Accent; label: string; className: string }[] = [
  { id: 'ivory', label: 'Ivory', className: 'bg-sky-700' }, { id: 'blue', label: 'Ocean', className: 'bg-sky-400' }, { id: 'violet', label: 'Violet', className: 'bg-violet-400' }, { id: 'emerald', label: 'Emerald', className: 'bg-emerald-400' }, { id: 'amber', label: 'Amber', className: 'bg-amber-400' },
];
export const SettingsScreen: React.FC<SettingsScreenProps> = ({ onBack, onNavigate, onPreferencesChange, onSignOut }) => {
  const [prefs, setPrefs] = useState<AppPreferences>(getPreferences);
  const update = (patch: Partial<AppPreferences>) => { const next = { ...prefs, ...patch }; setPrefs(next); localStorage.setItem('nextmarga_preferences', JSON.stringify(next)); onPreferencesChange?.(next); };
  useEffect(() => { document.documentElement.dataset.theme = prefs.theme; document.documentElement.dataset.accent = prefs.accent; document.documentElement.dataset.compact = String(prefs.compactMode); document.documentElement.dataset.reducedMotion = String(prefs.reducedMotion); }, [prefs]);
  const reset = () => { setPrefs(defaults); localStorage.setItem('nextmarga_preferences', JSON.stringify(defaults)); onPreferencesChange?.(defaults); };
  const handleSignOut = () => { if (window.confirm('Sign out of your NextMarga account?')) onSignOut?.(); };
  return <div className="min-h-screen bg-slate-50 text-slate-900 px-4 py-6 sm:px-6 pb-28"><div className="max-w-3xl mx-auto">
    <div className="flex items-center justify-between border-b border-slate-200 pb-5"><div className="flex items-center gap-3"><button onClick={onBack} className="p-2 rounded-lg border border-slate-200 hover:bg-sky-800/5"><ArrowLeft className="w-4 h-4" /></button><div><div className="text-[10px] uppercase tracking-[0.3em] text-slate-500 font-mono">Control Center</div><h1 className="font-serif-luxury text-2xl sm:text-3xl">Settings</h1></div></div><div className="hidden sm:flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-emerald-600/70"><span className="w-1.5 h-1.5 rounded-full bg-emerald-300" /> Preferences saved</div></div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><div className="flex items-center gap-2"><Palette className="w-4 h-4 text-slate-600" /><span className="text-xs uppercase tracking-[0.22em] font-mono text-slate-500">Appearance</span></div><p className="text-xs text-slate-500 mt-1">Make NextMarga feel like your workspace.</p></div><div className="p-5 space-y-6"><div><div className="text-xs font-medium mb-3">Theme</div><div className="rounded-xl border border-sky-200 bg-sky-50 p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-sky-700 border border-sky-100"><Check className="w-4 h-4" /></span><div><div className="text-sm font-semibold text-slate-900">Light workspace</div><div className="text-[11px] text-slate-600 mt-1">NextMarga uses one clean visual system across every screen.</div></div></div></div></div><div><div className="text-xs font-medium mb-3">Accent</div><div className="flex flex-wrap gap-3">{accents.map(a => <button key={a.id} onClick={() => update({ accent: a.id })} className="flex items-center gap-2 px-3 py-2 rounded-full border border-slate-200 hover:bg-sky-800/5"><span className={`w-3 h-3 rounded-full ${a.className}`} /> <span className="text-[11px] text-slate-700">{a.label}</span>{prefs.accent === a.id && <Check className="w-3 h-3" />}</button>)}</div></div></div></section>
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><div className="flex items-center gap-2"><Sparkles className="w-4 h-4 text-slate-600" /><span className="text-xs uppercase tracking-[0.22em] font-mono text-slate-500">Experience</span></div></div><div className="divide-y divide-slate-200">{[['compactMode','Compact interface','Fit more opportunities and information on screen.'],['reducedMotion','Reduce motion','Use simpler transitions and animations.'],['notifications','Opportunity alerts','Receive deadline, match and application notifications.']].map(([key,title,desc]) => <button key={key} onClick={() => update({ [key]: !prefs[key as keyof AppPreferences] } as Partial<AppPreferences>)} className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left hover:bg-sky-800/[0.03]"><div><div className="text-xs">{title}</div><div className="text-[11px] text-slate-400 mt-1">{desc}</div></div><span className={`w-10 h-5 rounded-full p-0.5 transition-colors ${prefs[key as keyof AppPreferences] ? 'bg-white' : 'bg-slate-100'}`}><span className={`block w-4 h-4 rounded-full transition-transform ${prefs[key as keyof AppPreferences] ? 'translate-x-5 bg-black' : 'bg-white/40'}`} /></span></button>)}</div></section>
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><div className="text-xs uppercase tracking-[0.22em] font-mono text-slate-500">Account & Profile</div></div><button onClick={() => onNavigate('profile')} className="w-full flex items-center justify-between px-5 py-4 hover:bg-sky-800/[0.03]"><span className="flex items-center gap-3"><UserRound className="w-4 h-4 text-slate-500" /><span><span className="block text-xs text-left">Profile & personal information</span><span className="block text-[11px] text-slate-400 mt-1">Update your academic and contact details</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button><button onClick={() => onNavigate('notifications')} className="w-full flex items-center justify-between px-5 py-4 border-t border-slate-200 hover:bg-sky-800/[0.03]"><span className="flex items-center gap-3"><Bell className="w-4 h-4 text-slate-500" /><span><span className="block text-xs text-left">Notification center</span><span className="block text-[11px] text-slate-400 mt-1">Review deadline and opportunity updates</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button></section>
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><div className="flex items-center gap-2"><UserRound className="w-4 h-4 text-slate-600" /><span className="text-xs uppercase tracking-[0.22em] font-mono text-slate-500">About the Author</span></div><p className="text-[11px] text-slate-400 mt-1">Meet the creator behind NextMarga.</p></div><div className="p-5"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 text-sm font-semibold">KA</div><div className="min-w-0"><h2 className="text-base font-medium">Kaif Ali</h2><p className="mt-1 text-[11px] uppercase tracking-[0.16em] text-slate-500">Creator & Developer · NextMarga</p><p className="mt-3 text-xs leading-6 text-slate-600">I am Kaif Ali, a student and developer building NextMarga to help students discover scholarships, competitions, exams, internships and other opportunities in one personalized platform. The goal is to make opportunity discovery simpler, more organized and more accessible for students.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><a href="https://instagram.com/kaif9.645" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3 hover:bg-sky-800/5"><span className="flex items-center gap-3"><Instagram className="w-4 h-4 text-slate-600" /><span><span className="block text-xs">Instagram</span><span className="block text-[11px] text-slate-400">@kaif9.645</span></span></span><ExternalLink className="w-3.5 h-3.5 text-slate-400" /></a><a href="https://github.com/rkaif8314-a11y" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3 hover:bg-sky-800/5"><span className="flex items-center gap-3"><Github className="w-4 h-4 text-slate-600" /><span><span className="block text-xs">GitHub</span><span className="block text-[11px] text-slate-400">@rkaif8314-a11y</span></span></span><ExternalLink className="w-3.5 h-3.5 text-slate-400" /></a></div></div></section>
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><div className="text-xs uppercase tracking-[0.22em] font-mono text-slate-500">Legal & Trust</div><p className="text-[11px] text-slate-400 mt-1">Policies, verification standards and support.</p></div><button onClick={() => onNavigate('legal-privacy')} className="w-full flex items-center justify-between px-5 py-4 hover:bg-sky-800/[0.03]"><span className="flex items-center gap-3"><Shield className="w-4 h-4 text-slate-500" /><span><span className="block text-xs text-left">Privacy Policy</span><span className="block text-[11px] text-slate-400 mt-1">How NextMarga handles account and product data</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button><button onClick={() => onNavigate('legal-terms')} className="w-full flex items-center justify-between px-5 py-4 border-t border-slate-200 hover:bg-sky-800/[0.03]"><span className="flex items-center gap-3"><FileText className="w-4 h-4 text-slate-500" /><span><span className="block text-xs text-left">Terms of Service</span><span className="block text-[11px] text-slate-400 mt-1">Rules for using NextMarga and opportunity listings</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button><button onClick={() => onNavigate('legal-verification')} className="w-full flex items-center justify-between px-5 py-4 border-t border-slate-200 hover:bg-sky-800/[0.03]"><span className="flex items-center gap-3"><Shield className="w-4 h-4 text-slate-500" /><span><span className="block text-xs text-left">Verification Policy</span><span className="block text-[11px] text-slate-400 mt-1">How opportunity sources and freshness are reviewed</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button><button onClick={() => onNavigate('support')} className="w-full flex items-center justify-between px-5 py-4 border-t border-slate-200 hover:bg-sky-800/[0.03]"><span className="flex items-center gap-3"><Flag className="w-4 h-4 text-slate-500" /><span><span className="block text-xs text-left">Help & report an issue</span><span className="block text-[11px] text-slate-400 mt-1">Report broken or incorrect opportunities</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button></section>
    <section className="mt-4 rounded-2xl border border-red-400/15 bg-red-400/[0.03] overflow-hidden"><div className="px-5 py-4 border-b border-red-400/10"><div className="text-xs uppercase tracking-[0.22em] font-mono text-red-700/60">Session</div><p className="text-[11px] text-slate-400 mt-1">Sign out of this NextMarga account on this device.</p></div><button onClick={handleSignOut} className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-red-50 transition-colors"><span className="flex items-center gap-3"><span className="flex items-center justify-center w-8 h-8 rounded-lg border border-red-300/15 bg-red-300/5"><LogOut className="w-4 h-4 text-red-700/70" /></span><span><span className="block text-xs text-red-700">Log out</span><span className="block text-[11px] text-slate-400 mt-1">End your current session securely</span></span></span><ChevronRight className="w-4 h-4 text-slate-400" /></button></section>
    <button onClick={reset} className="mt-5 w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-slate-200 text-[10px] uppercase tracking-[0.18em] text-slate-500 hover:text-slate-950 hover:bg-sky-800/5"><RotateCcw className="w-3.5 h-3.5" /> Reset appearance & preferences</button><div className="mt-6 flex items-center justify-center gap-2 text-[9px] uppercase tracking-[0.25em] text-slate-950/20 font-mono"><Shield className="w-3 h-3" /> Your preferences stay on this device</div>
  </div></div>;
};
